### ISSUE TITLE
Run for debugPrint too?

### ISSUE THREAD

**Issue by bagintz** [DevPrinceK/print_slayer#1]
This has been super handy, can you give it an option to remove debugPrint's too?

**Comment by DevPrinceK** [comment]
> This has been super handy, can you give it an option to remove debugPrint's too?

Yes! It's in the next update which should be out in a couple of days. Thanks so much for your valuable suggestions.

**Comment by bagintz** [comment]
lol, nice!  I just removed 732 debugPrint's manually, wish I had waited :)

**Comment by DevPrinceK** [comment]
> lol, nice! I just removed 732 debugPrint's manually, wish I had waited :)

That's crazy!
Hopefully this will be the last time. lol.

**Comment by bagintz** [comment]
Did you release the version for debugPrint's too?

**Comment by DevPrinceK** [comment]
@bagintz 
Checkout version 1.1.0 for the requested updated.
Cheers!

**Comment by DevPrinceK** [comment]
https://pub.dev/packages/print_slayer
